<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btnLogin</name>
   <tag></tag>
   <elementGuidId>7463172b-5ab2-4662-aeba-0d27b3a3d134</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//a[@id=&quot;login2&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//a[@id=&quot;login2&quot;]</value>
      <webElementGuid>1dc2f94c-26a8-4ae6-bad2-d2ec24e53c14</webElementGuid>
   </webElementProperties>
</WebElementEntity>
