<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btnToLogin</name>
   <tag></tag>
   <elementGuidId>d37bb795-9e15-4360-8e74-4e40bf54c6a7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;logInModal&quot;]/div/div/div[3]/button[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;logInModal&quot;]/div/div/div[3]/button[2]</value>
      <webElementGuid>92cee7a2-035e-487b-98e6-de2abd779ee9</webElementGuid>
   </webElementProperties>
</WebElementEntity>
